FROM ghcr.io/mohitt/windows-playwright-docker:latest

WORKDIR /app/tests

# Copy and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the test project
COPY ./ ./

ENTRYPOINT ["powershell", "-Command", "npx playwright install chromium --with-deps; npm run test"]
